name: Post

on:
  schedule:
    - cron: '0 1 * * *' # runs at 10:00 JST everyday
  workflow_dispatch:

jobs:
  astro-ph-ga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install arxiv-post==0.6.4
          playwright install chromium
      - name: Post articles to Slack
        run: |
          arxiv-post slack \
            --categories astro-ph.GA \
            --target_lang ja \
            --slack_webhook_url ${{ secrets.SLACK_WEBHOOK_URL_GA }} \
            --debug
  astro-ph-im:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install arxiv-post==0.6.4
          playwright install chromium
      - name: Post articles to Slack
        run: |
          arxiv-post slack \
            --categories astro-ph.IM \
            --target_lang ja \
            --slack_webhook_url ${{ secrets.SLACK_WEBHOOK_URL_IM }} \
            --deepl_api_key ${{ secrets.DEEPL_API_KEY }} \
            --debug
  astro-ph-he:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install arxiv-post==0.6.4
          playwright install chromium
      - name: Post articles to Slack
        run: |
          arxiv-post slack \
            --categories astro-ph.HE \
            --target_lang ja \
            --slack_webhook_url ${{ secrets.SLACK_WEBHOOK_URL_HE }} \
            --debug
