name: Post

on:
  schedule:
    - cron: '0 1 * * *' # runs at 10:00 JST everyday
  workflow_dispatch:

jobs:
  astro-ph-GA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install astro-ph==0.3.1
          playwright install chromium
      - name: Post articles to Slack
        run: |
          astro-ph slack \
            --categories astro-ph.GA \
            --language_to ja \
            --webhook_url ${{ secrets.SLACK_WEBHOOK_GA }} \
            --n_concurrent 4 \
            --debug
  astro-ph-IM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install astro-ph==0.3.1
          playwright install chromium
      - name: Post articles to Slack
        run: |
          astro-ph slack \
            --categories astro-ph.IM \
            --language_to ja \
            --webhook_url ${{ secrets.SLACK_WEBHOOK_IM }} \
            --n_concurrent 4 \
            --debug
